#spring.application.name=AngkorLeving_Backend
#
#
##pring.application.name=backendAngkorLiving
#
## Database (use env vars instead of hardcoding)
#spring.datasource.url=${DATABASE_URL}
#spring.datasource.username=${DATABASE_USERNAME}
#spring.datasource.password=${DATABASE_PASSWORD}
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
## Server port (Render injects $PORT automatically)
#server.port=${PORT:8080}
#
## JWT secret key
#jwt.secret=${JWT_SECRET}
#
## Cloudinary
#cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
#cloudinary.api_key=${CLOUDINARY_API_KEY}
#cloudinary.api_secret=${CLOUDINARY_API_SECRET}
#
## Bakong / NBC API
#BAKONG_ACCOUNT_USERNAME=${BAKONG_ACCOUNT_USERNAME}
#BAKONG_ACCOUNT_NAME=${BAKONG_ACCOUNT_NAME}
#BAKONG_LOCATION=${BAKONG_LOCATION}
#NBC_API_URL=${NBC_API_URL}
#BAKONG_API_TOKEN=${BAKONG_API_TOKEN}

spring.datasource.url=jdbc:postgresql://localhost:5432/Angkorlivingdatabase
spring.datasource.username=postgres
spring.datasource.password=mora123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=mySuperSecretKeyForJwt1234567890ABCDEF
cloudinary.cloud_name=dz82bkh4t
cloudinary.api_key=158524144752832
cloudinary.api_secret=UM0S7iC1u14jVeQ6sCuebBKlQkU
BAKONG_ACCOUNT-ID=somora_march@bkrt
BAKONG_ACCOUNT_NAME=MoraComputer
BAKONG_LOCATION=PhnomPenh
BAKONG.BASE-URL=https://api-bakong.nbc.gov.kh/
bakong.verify-url=https://api-bakong.nbc.gov.kh/v1/check_transaction_by_md5
bakong.email=marchsomora8@gmail.com
BAKONG_API_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
